/*
ADU_MT_HCP_HCO_AFFILIATION
Purpose
    - ADU Affiliation data for HCPs and HCOs with the Health care system information mapped
Change Log
    - 2021-07-14 - vshetiya - Created

*/

USE ROLE __SNOWFLAKE_NGCA_CIM_DEPLOY_RL__; 


CREATE OR REPLACE VIEW __SNOWFLAKE_NGCA_DB__.MCE.ADU_MT_HCP_HCO_AFFILIATION
COMMENT = 'VIEW CONTAINING THE ADU AFFILIATION DATA FOR HCPs AND HCOs'
AS
(
SELECT 
	PARENT_ID,
	PARENT_NAME,
	PARENT_TYPE,
	CHILD_ID,
	CHILD_NAME,
	CHILD_TYPE,
	HEALTH_CARE_SYSTEM,
	AFFILIATION_TYPE,
	STATUS,
/* Adding flex columns to ease the integration process if we need to add additional fields in the data */
	NULL AS ATTRIBUTE_NAME_1,
	NULL AS ATTRIBUTE_VALUE_1,
	NULL AS ATTRIBUTE_NAME_2,
	NULL AS ATTRIBUTE_VALUE_2,
	NULL AS ATTRIBUTE_NAME_3,
	NULL AS ATTRIBUTE_VALUE_3,
	NULL AS ATTRIBUTE_NAME_4,
	NULL AS ATTRIBUTE_VALUE_4,
	NULL AS ATTRIBUTE_NAME_5,
	NULL AS ATTRIBUTE_VALUE_5
FROM	
(
WITH 
vnt_hco AS (SELECT MK_ACCOUNT_VNT_ID,HCO_TYPE__V,CORPORATE_NAME__V,AD_INFUSION_SITE__C,
                   MAJOR_CLASS_OF_TRADE__V,RECORD_STATE__V,HCO_STATUS__V,PRIMARY_COUNTRY__V
            FROM __SNOWFLAKE_NGDW_DB__.INTEGRATED.VNT_HCO_SCD1 
            WHERE RECORD_STATE__V = 'VALID'
           ),
vnt_hcp AS (SELECT MK_ACCOUNT_VNT_ID,FORMATTED_NAME__V,NPI_NUM__V FROM __SNOWFLAKE_NGDW_DB__.INTEGRATED.VNT_HCP_SCD1 
            WHERE RECORD_STATE__V = 'VALID'
           ),			
affiliation AS (SELECT MK_ACCOUNT_VNT_ID,MK_PARENT_ACCOUNT_VNT_ID,MODIFIED_DATE__V,RECORD_STATE__V,AD_PRIMARY_AFFILIATION__C,INGESTION_DATE,HIERARCHY_TYPE__V,
                       AD_INFUSION_TREATMENT_LOCATION__C,AD_LP_SCAN_LOCATION__C,AD_MRI_SCAN_LOCATION__C,AD_NEUROCOGNITIVE_TESTING_LOCATION__C,AD_PET_SCAN_LOCATION__C
                FROM __SNOWFLAKE_NGDW_DB__.INTEGRATED.VNT_PARENTHCO_SCD1
                WHERE RECORD_STATE__V = 'VALID'
                AND MK_PARENT_ACCOUNT_VNT_ID <> '-1' AND MK_PARENT_ACCOUNT_VNT_ID IS NOT NULL
                AND MK_ACCOUNT_VNT_ID <> '-1' AND MK_ACCOUNT_VNT_ID IS NOT NULL),
act_dim AS (SELECT MK_ACCOUNT_VNT_ID,IS_AD_MARKET,ACCOUNT_CLASS,ACCOUNT_NAME FROM __SNOWFLAKE_NGDW_DB__.SEMANTIC.VNT_ACCOUNT_DIM
		    WHERE RECORD_STATE = 'VALID'  
		    AND MK_ACCOUNT_VNT_ID IS NOT NULL 
            AND MK_ACCOUNT_VNT_ID <> '-1'
           ),
vnt_parenthco AS (
			SELECT affiliation.MK_ACCOUNT_VNT_ID
				,affiliation.MK_PARENT_ACCOUNT_VNT_ID
				,affiliation.MODIFIED_DATE__V
			FROM affiliation
			WHERE affiliation.AD_PRIMARY_AFFILIATION__C = 'Y'
				QUALIFY ROW_NUMBER() OVER (PARTITION BY affiliation.MK_ACCOUNT_VNT_ID ORDER BY affiliation.MODIFIED_DATE__V DESC NULLS LAST) = 1
                 ),
infusion_site AS (
			SELECT AD_INFUSION_SITE__C,
			'Y' AS MASTER_SITE__C
				,MK_ACCOUNT_VNT_ID
                ,CORPORATE_NAME__V
			FROM vnt_hco
			WHERE RECORD_STATE__V = 'VALID'
			AND HCO_STATUS__V = 'A'
			AND PRIMARY_COUNTRY__V = 'US'
			),
health_care_system AS (
	SELECT
	vnt_hco.MK_ACCOUNT_VNT_ID AS ACCOUNT_VNID,
	vnt_hco.CORPORATE_NAME__V AS ACCOUNT_NAME,
	CASE WHEN (prnt_prnt_vnt_hco.HCO_TYPE__V = '4:37' OR prnt_prnt_vnt_hco.HCO_TYPE__V = '26:13')
		  THEN prnt_prnt_vnt_hco.CORPORATE_NAME__V
		  WHEN (prnt_vnt_hco.HCO_TYPE__V = '4:37' OR prnt_vnt_hco.HCO_TYPE__V = '26:13')
		  THEN prnt_vnt_hco.CORPORATE_NAME__V
          WHEN (vnt_hco.HCO_TYPE__V = '4:37' OR vnt_hco.HCO_TYPE__V = '26:13')
          THEN vnt_hco.CORPORATE_NAME__V
	ELSE NULL END AS FINAL_HEALTH_SYSTEM_NAME
	FROM VNT_HCO vnt_hco
	LEFT JOIN VNT_PARENTHCO vnt_parenthco
	  ON vnt_hco.MK_ACCOUNT_VNT_ID = vnt_parenthco.MK_ACCOUNT_VNT_ID
	LEFT JOIN VNT_PARENTHCO prnt_vnt_parenthco
	  ON vnt_parenthco.MK_PARENT_ACCOUNT_VNT_ID = prnt_vnt_parenthco.MK_ACCOUNT_VNT_ID
	LEFT JOIN  VNT_HCO prnt_vnt_hco
	  ON prnt_vnt_hco.MK_ACCOUNT_VNT_ID = vnt_parenthco.MK_PARENT_ACCOUNT_VNT_ID
	LEFT JOIN  VNT_HCO prnt_prnt_vnt_hco
	ON prnt_vnt_parenthco.MK_PARENT_ACCOUNT_VNT_ID = prnt_prnt_vnt_hco.MK_ACCOUNT_VNT_ID
	GROUP BY ACCOUNT_VNID,ACCOUNT_NAME,FINAL_HEALTH_SYSTEM_NAME
	) 			

  
SELECT
	affiliation.MK_PARENT_ACCOUNT_VNT_ID AS PARENT_ID,		
    NVL(act_dim_parent.ACCOUNT_NAME,vnt_hco_parent.CORPORATE_NAME__V) AS PARENT_NAME,
    NVL(act_dim_parent.ACCOUNT_CLASS,'HCO') AS PARENT_TYPE,
	affiliation.MK_ACCOUNT_VNT_ID AS CHILD_ID,
    COALESCE(act_dim_child.ACCOUNT_NAME,vnt_hco_child.CORPORATE_NAME__V,vnt_hcp.FORMATTED_NAME__V) AS CHILD_NAME,
    CASE WHEN infusion_site.AD_INFUSION_SITE__C = 'Y' THEN 'INFUSION FACILITY' 
	ELSE NVL(act_dim_child.ACCOUNT_CLASS,SUBSTR(affiliation.HIERARCHY_TYPE__V,1,3)) END AS CHILD_TYPE,  
    health_care_system.FINAL_HEALTH_SYSTEM_NAME AS HEALTH_CARE_SYSTEM,
    'PRIMARY AD AFFILIATION' AS AFFILIATION_TYPE,
	affiliation.RECORD_STATE__V AS STATUS
    
FROM affiliation
LEFT JOIN vnt_hco vnt_hco_parent ON affiliation.MK_PARENT_ACCOUNT_VNT_ID = vnt_hco_parent.MK_ACCOUNT_VNT_ID
LEFT JOIN act_dim act_dim_parent ON affiliation.MK_PARENT_ACCOUNT_VNT_ID = act_dim_parent.MK_ACCOUNT_VNT_ID	
LEFT JOIN vnt_hco vnt_hco_child ON affiliation.MK_ACCOUNT_VNT_ID = vnt_hco_child.MK_ACCOUNT_VNT_ID
LEFT JOIN vnt_hcp ON affiliation.MK_ACCOUNT_VNT_ID = vnt_hcp.MK_ACCOUNT_VNT_ID
LEFT JOIN act_dim act_dim_child ON affiliation.MK_ACCOUNT_VNT_ID = act_dim_child.MK_ACCOUNT_VNT_ID	
LEFT JOIN health_care_system ON affiliation.MK_PARENT_ACCOUNT_VNT_ID = health_care_system.ACCOUNT_VNID
LEFT JOIN infusion_site ON affiliation.MK_ACCOUNT_VNT_ID = infusion_site.MK_ACCOUNT_VNT_ID

WHERE affiliation.AD_PRIMARY_AFFILIATION__C = 'Y'
QUALIFY ROW_NUMBER() OVER (PARTITION BY PARENT_ID,CHILD_ID ORDER BY affiliation.MODIFIED_DATE__V DESC) = 1  
  

UNION ALL 

SELECT
	affiliation.MK_PARENT_ACCOUNT_VNT_ID AS PARENT_ID,		
    NVL(act_dim_parent.ACCOUNT_NAME,vnt_hco_parent.CORPORATE_NAME__V) AS PARENT_NAME,
    NVL(act_dim_parent.ACCOUNT_CLASS,'HCO') AS PARENT_TYPE,
	affiliation.MK_ACCOUNT_VNT_ID AS CHILD_ID,
    COALESCE(act_dim_child.ACCOUNT_NAME,vnt_hco_child.CORPORATE_NAME__V,vnt_hcp.FORMATTED_NAME__V) AS CHILD_NAME,
    CASE WHEN infusion_site.AD_INFUSION_SITE__C = 'Y' THEN 'INFUSION FACILITY' 
	ELSE NVL(act_dim_child.ACCOUNT_CLASS,SUBSTR(affiliation.HIERARCHY_TYPE__V,1,3)) END AS CHILD_TYPE,  
    health_care_system.FINAL_HEALTH_SYSTEM_NAME AS HEALTH_CARE_SYSTEM,
    CASE WHEN UPPER(affiliation.AD_INFUSION_TREATMENT_LOCATION__C) = 'PRIMARY__C' THEN 'PRIMARY AD INFUSION TREATMENT LOCATION' 
    ELSE 'SECONDARY AD INFUSION TREATMENT LOCATION' END AS AFFILIATION_TYPE,
	affiliation.RECORD_STATE__V AS STATUS
    
FROM affiliation
LEFT JOIN vnt_hco vnt_hco_parent ON affiliation.MK_PARENT_ACCOUNT_VNT_ID = vnt_hco_parent.MK_ACCOUNT_VNT_ID
LEFT JOIN act_dim act_dim_parent ON affiliation.MK_PARENT_ACCOUNT_VNT_ID = act_dim_parent.MK_ACCOUNT_VNT_ID	
LEFT JOIN vnt_hco vnt_hco_child ON affiliation.MK_ACCOUNT_VNT_ID = vnt_hco_child.MK_ACCOUNT_VNT_ID
LEFT JOIN vnt_hcp ON affiliation.MK_ACCOUNT_VNT_ID = vnt_hcp.MK_ACCOUNT_VNT_ID
LEFT JOIN act_dim act_dim_child ON affiliation.MK_ACCOUNT_VNT_ID = act_dim_child.MK_ACCOUNT_VNT_ID	
LEFT JOIN health_care_system ON affiliation.MK_PARENT_ACCOUNT_VNT_ID = health_care_system.ACCOUNT_VNID
LEFT JOIN infusion_site ON affiliation.MK_ACCOUNT_VNT_ID = infusion_site.MK_ACCOUNT_VNT_ID

WHERE UPPER(affiliation.AD_INFUSION_TREATMENT_LOCATION__C) IN ('PRIMARY__C','SECONDARY__C')
QUALIFY ROW_NUMBER() OVER (PARTITION BY PARENT_ID,CHILD_ID ORDER BY affiliation.MODIFIED_DATE__V DESC) = 1  

UNION ALL 

SELECT
	affiliation.MK_PARENT_ACCOUNT_VNT_ID AS PARENT_ID,		
    NVL(act_dim_parent.ACCOUNT_NAME,vnt_hco_parent.CORPORATE_NAME__V) AS PARENT_NAME,
    NVL(act_dim_parent.ACCOUNT_CLASS,'HCO') AS PARENT_TYPE,
	affiliation.MK_ACCOUNT_VNT_ID AS CHILD_ID,
    COALESCE(act_dim_child.ACCOUNT_NAME,vnt_hco_child.CORPORATE_NAME__V,vnt_hcp.FORMATTED_NAME__V) AS CHILD_NAME,
    CASE WHEN infusion_site.AD_INFUSION_SITE__C = 'Y' THEN 'INFUSION FACILITY' 
	ELSE NVL(act_dim_child.ACCOUNT_CLASS,SUBSTR(affiliation.HIERARCHY_TYPE__V,1,3)) END AS CHILD_TYPE,  
    health_care_system.FINAL_HEALTH_SYSTEM_NAME AS HEALTH_CARE_SYSTEM,
    CASE WHEN UPPER(affiliation.AD_LP_SCAN_LOCATION__C) = 'PRIMARY__C' THEN 'PRIMARY AD LP SCAN LOCATION' 
    ELSE 'SECONDARY AD LP SCAN LOCATION' END AS AFFILIATION_TYPE,
	affiliation.RECORD_STATE__V AS STATUS
    
FROM affiliation
LEFT JOIN vnt_hco vnt_hco_parent ON affiliation.MK_PARENT_ACCOUNT_VNT_ID = vnt_hco_parent.MK_ACCOUNT_VNT_ID
LEFT JOIN act_dim act_dim_parent ON affiliation.MK_PARENT_ACCOUNT_VNT_ID = act_dim_parent.MK_ACCOUNT_VNT_ID	
LEFT JOIN vnt_hco vnt_hco_child ON affiliation.MK_ACCOUNT_VNT_ID = vnt_hco_child.MK_ACCOUNT_VNT_ID
LEFT JOIN vnt_hcp ON affiliation.MK_ACCOUNT_VNT_ID = vnt_hcp.MK_ACCOUNT_VNT_ID
LEFT JOIN act_dim act_dim_child ON affiliation.MK_ACCOUNT_VNT_ID = act_dim_child.MK_ACCOUNT_VNT_ID	
LEFT JOIN health_care_system ON affiliation.MK_PARENT_ACCOUNT_VNT_ID = health_care_system.ACCOUNT_VNID
LEFT JOIN infusion_site ON affiliation.MK_ACCOUNT_VNT_ID = infusion_site.MK_ACCOUNT_VNT_ID

WHERE UPPER(affiliation.AD_LP_SCAN_LOCATION__C) IN ('PRIMARY__C','SECONDARY__C')
QUALIFY ROW_NUMBER() OVER (PARTITION BY PARENT_ID,CHILD_ID ORDER BY affiliation.MODIFIED_DATE__V DESC) = 1  
  
UNION ALL 

SELECT
	affiliation.MK_PARENT_ACCOUNT_VNT_ID AS PARENT_ID,		
    NVL(act_dim_parent.ACCOUNT_NAME,vnt_hco_parent.CORPORATE_NAME__V) AS PARENT_NAME,
    NVL(act_dim_parent.ACCOUNT_CLASS,'HCO') AS PARENT_TYPE,
	affiliation.MK_ACCOUNT_VNT_ID AS CHILD_ID,
    COALESCE(act_dim_child.ACCOUNT_NAME,vnt_hco_child.CORPORATE_NAME__V,vnt_hcp.FORMATTED_NAME__V) AS CHILD_NAME,
    CASE WHEN infusion_site.AD_INFUSION_SITE__C = 'Y' THEN 'INFUSION FACILITY' 
	ELSE NVL(act_dim_child.ACCOUNT_CLASS,SUBSTR(affiliation.HIERARCHY_TYPE__V,1,3)) END AS CHILD_TYPE,  
    health_care_system.FINAL_HEALTH_SYSTEM_NAME AS HEALTH_CARE_SYSTEM,
    CASE WHEN UPPER(affiliation.AD_MRI_SCAN_LOCATION__C) = 'PRIMARY__C' THEN 'PRIMARY AD MRI SCAN LOCATION' 
    ELSE 'SECONDARY AD MRI SCAN LOCATION' END AS AFFILIATION_TYPE,
	affiliation.RECORD_STATE__V AS STATUS
    
FROM affiliation
LEFT JOIN vnt_hco vnt_hco_parent ON affiliation.MK_PARENT_ACCOUNT_VNT_ID = vnt_hco_parent.MK_ACCOUNT_VNT_ID
LEFT JOIN act_dim act_dim_parent ON affiliation.MK_PARENT_ACCOUNT_VNT_ID = act_dim_parent.MK_ACCOUNT_VNT_ID	
LEFT JOIN vnt_hco vnt_hco_child ON affiliation.MK_ACCOUNT_VNT_ID = vnt_hco_child.MK_ACCOUNT_VNT_ID
LEFT JOIN vnt_hcp ON affiliation.MK_ACCOUNT_VNT_ID = vnt_hcp.MK_ACCOUNT_VNT_ID
LEFT JOIN act_dim act_dim_child ON affiliation.MK_ACCOUNT_VNT_ID = act_dim_child.MK_ACCOUNT_VNT_ID	
LEFT JOIN health_care_system ON affiliation.MK_PARENT_ACCOUNT_VNT_ID = health_care_system.ACCOUNT_VNID
LEFT JOIN infusion_site ON affiliation.MK_ACCOUNT_VNT_ID = infusion_site.MK_ACCOUNT_VNT_ID

WHERE UPPER(affiliation.AD_MRI_SCAN_LOCATION__C) IN ('PRIMARY__C','SECONDARY__C')
QUALIFY ROW_NUMBER() OVER (PARTITION BY PARENT_ID,CHILD_ID ORDER BY affiliation.MODIFIED_DATE__V DESC) = 1  

UNION ALL 

SELECT
	affiliation.MK_PARENT_ACCOUNT_VNT_ID AS PARENT_ID,		
    NVL(act_dim_parent.ACCOUNT_NAME,vnt_hco_parent.CORPORATE_NAME__V) AS PARENT_NAME,
    NVL(act_dim_parent.ACCOUNT_CLASS,'HCO') AS PARENT_TYPE,
	affiliation.MK_ACCOUNT_VNT_ID AS CHILD_ID,
    COALESCE(act_dim_child.ACCOUNT_NAME,vnt_hco_child.CORPORATE_NAME__V,vnt_hcp.FORMATTED_NAME__V) AS CHILD_NAME,
    CASE WHEN infusion_site.AD_INFUSION_SITE__C = 'Y' THEN 'INFUSION FACILITY' 
	ELSE NVL(act_dim_child.ACCOUNT_CLASS,SUBSTR(affiliation.HIERARCHY_TYPE__V,1,3)) END AS CHILD_TYPE,  
    health_care_system.FINAL_HEALTH_SYSTEM_NAME AS HEALTH_CARE_SYSTEM,
    CASE WHEN UPPER(affiliation.AD_NEUROCOGNITIVE_TESTING_LOCATION__C) = 'PRIMARY__C' THEN 'PRIMARY AD NEUROCOGNITIVE TESTING LOCATION' 
    ELSE 'SECONDARY AD NEUROCOGNITIVE TESTING LOCATION' END AS AFFILIATION_TYPE,
	affiliation.RECORD_STATE__V AS STATUS
    
FROM affiliation
LEFT JOIN vnt_hco vnt_hco_parent ON affiliation.MK_PARENT_ACCOUNT_VNT_ID = vnt_hco_parent.MK_ACCOUNT_VNT_ID
LEFT JOIN act_dim act_dim_parent ON affiliation.MK_PARENT_ACCOUNT_VNT_ID = act_dim_parent.MK_ACCOUNT_VNT_ID	
LEFT JOIN vnt_hco vnt_hco_child ON affiliation.MK_ACCOUNT_VNT_ID = vnt_hco_child.MK_ACCOUNT_VNT_ID
LEFT JOIN vnt_hcp ON affiliation.MK_ACCOUNT_VNT_ID = vnt_hcp.MK_ACCOUNT_VNT_ID
LEFT JOIN act_dim act_dim_child ON affiliation.MK_ACCOUNT_VNT_ID = act_dim_child.MK_ACCOUNT_VNT_ID	
LEFT JOIN health_care_system ON affiliation.MK_PARENT_ACCOUNT_VNT_ID = health_care_system.ACCOUNT_VNID
LEFT JOIN infusion_site ON affiliation.MK_ACCOUNT_VNT_ID = infusion_site.MK_ACCOUNT_VNT_ID

WHERE UPPER(affiliation.AD_NEUROCOGNITIVE_TESTING_LOCATION__C) IN ('PRIMARY__C','SECONDARY__C')
QUALIFY ROW_NUMBER() OVER (PARTITION BY PARENT_ID,CHILD_ID ORDER BY affiliation.MODIFIED_DATE__V DESC) = 1  
  
UNION ALL 

SELECT
	affiliation.MK_PARENT_ACCOUNT_VNT_ID AS PARENT_ID,		
    NVL(act_dim_parent.ACCOUNT_NAME,vnt_hco_parent.CORPORATE_NAME__V) AS PARENT_NAME,
    NVL(act_dim_parent.ACCOUNT_CLASS,'HCO') AS PARENT_TYPE,
	affiliation.MK_ACCOUNT_VNT_ID AS CHILD_ID,
    COALESCE(act_dim_child.ACCOUNT_NAME,vnt_hco_child.CORPORATE_NAME__V,vnt_hcp.FORMATTED_NAME__V) AS CHILD_NAME,
    CASE WHEN infusion_site.AD_INFUSION_SITE__C = 'Y' THEN 'INFUSION FACILITY' 
	ELSE NVL(act_dim_child.ACCOUNT_CLASS,SUBSTR(affiliation.HIERARCHY_TYPE__V,1,3)) END AS CHILD_TYPE,  
    health_care_system.FINAL_HEALTH_SYSTEM_NAME AS HEALTH_CARE_SYSTEM,
    CASE WHEN UPPER(affiliation.AD_PET_SCAN_LOCATION__C) = 'PRIMARY__C' THEN 'PRIMARY AD PET SCAN LOCATION' 
    ELSE 'SECONDARY AD PET SCAN LOCATION' END AS AFFILIATION_TYPE,
	affiliation.RECORD_STATE__V AS STATUS
    
FROM affiliation
LEFT JOIN vnt_hco vnt_hco_parent ON affiliation.MK_PARENT_ACCOUNT_VNT_ID = vnt_hco_parent.MK_ACCOUNT_VNT_ID
LEFT JOIN act_dim act_dim_parent ON affiliation.MK_PARENT_ACCOUNT_VNT_ID = act_dim_parent.MK_ACCOUNT_VNT_ID	
LEFT JOIN vnt_hco vnt_hco_child ON affiliation.MK_ACCOUNT_VNT_ID = vnt_hco_child.MK_ACCOUNT_VNT_ID
LEFT JOIN vnt_hcp ON affiliation.MK_ACCOUNT_VNT_ID = vnt_hcp.MK_ACCOUNT_VNT_ID
LEFT JOIN act_dim act_dim_child ON affiliation.MK_ACCOUNT_VNT_ID = act_dim_child.MK_ACCOUNT_VNT_ID	
LEFT JOIN health_care_system ON affiliation.MK_PARENT_ACCOUNT_VNT_ID = health_care_system.ACCOUNT_VNID
LEFT JOIN infusion_site ON affiliation.MK_ACCOUNT_VNT_ID = infusion_site.MK_ACCOUNT_VNT_ID

WHERE UPPER(affiliation.AD_PET_SCAN_LOCATION__C) IN ('PRIMARY__C','SECONDARY__C')
QUALIFY ROW_NUMBER() OVER (PARTITION BY PARENT_ID,CHILD_ID ORDER BY affiliation.MODIFIED_DATE__V DESC) = 1  

)
WHERE PARENT_NAME IS NOT NULL AND CHILD_NAME IS NOT NULL
);

GRANT SELECT ON __SNOWFLAKE_NGCA_DB__.MCE.ADU_MT_HCP_HCO_AFFILIATION TO ROLE IHUB_QRY_RL; 
