/*
ALZ_TARGET_HCP_LIST
Purpose
    - STATIC TABLE TO MAP THE ALZ HCP WITH THE SEGMENT AND DECILE INFO
Change Log
    - 2021-07-26 - vshetiya - Created


*/ 
USE ROLE __SNOWFLAKE_NGCA_CIM_DEPLOY_RL__; 

CREATE TABLE IF NOT EXISTS __SNOWFLAKE_NGCA_DB__.MCE.ALZ_TARGET_HCP_LIST 
COMMENT = 'STATIC TABLE FOR THE PROFILIING OF ALZ TARGET HCP BASED ON NPI NUMBER'
(
	ID VARCHAR(255),
	PROVIDER_ID VARCHAR(255),
	NPI VARCHAR(255),
	NAME VARCHAR(255),
	ADDRESS VARCHAR(255),
	CITY VARCHAR(255),
	STATE VARCHAR(255),
	ZIP VARCHAR(255),
	SPECIALTY VARCHAR(255),
    NEUROS VARCHAR (255),
    PCPS VARCHAR (255),  
	GRANULAR_SPECIALTY VARCHAR(255),
	SEGMENT VARCHAR(255),
    BIIB_GROUP VARCHAR(255),
    GROUP_A VARCHAR(255),
    GROUP_B VARCHAR(255),
    GROUP_C VARCHAR(255),
    INITIATOR_TREATOR VARCHAR(255),
    INITIATOR_COUNT VARCHAR(255),
    TREATOR_COUNT VARCHAR(255),
    TOTAL_INITIATIONS VARCHAR(255),
    SYMPTOMATIC_TRX VARCHAR(255),
    PATIENT_VOLUME VARCHAR(255),
    COMPOSITE_DECILE VARCHAR(255),
    KME_HCP_FLAG VARCHAR(255),
    KME_COUNT VARCHAR(255),
    TBM_TERRITORY_ID VARCHAR(255),
    TBM_TERRITORY VARCHAR(255),
    TBM_REGION_ID VARCHAR(255),
    TBM_REGION VARCHAR(255),
    TBM_ZONE_ID VARCHAR(255),
    TBM_ZONE VARCHAR(255),
    AAL_TERRITORY_ID VARCHAR(255),
    AAL_TERRITORY VARCHAR(255),
    AAL_REGION_ID VARCHAR(255),
    AAL_REGION VARCHAR(255),
    ADRM_TERRITORY_ID VARCHAR(255),
    ADRM_TERRITORY VARCHAR(255),
    ADRM_REGION_ID VARCHAR(255),
    ADRM_REGION VARCHAR(255),
    ACCOUNT VARCHAR(255),
    PARENT_ID VARCHAR(255),
    TIER VARCHAR(255),
    SOC VARCHAR(255)
);

GRANT SELECT ON __SNOWFLAKE_NGCA_DB__.MCE.ALZ_TARGET_HCP_LIST TO ROLE IHUB_QRY_RL; 