
/*
SFMC_EMAIL_ENG_FINAL
Purpose
    - Aggregated SFMC Email Data of HCP and Patients with additional tactic code attributes  
Change Log
    - 2021-05-12 - vshetiya - Created
    - 2021-07-28 - vshetiya - Updated field names and added lead source field




*/

USE ROLE __SNOWFLAKE_NGCA_CIM_DEPLOY_RL__; 


CREATE OR REPLACE VIEW NGCA_DEV.MCE.SFMC_EMAIL_ENG_FINAL 
comment = 'AGGREGATED SFMC EMAIL DATA FOR HCP AND PATIENTS' AS
(
SELECT  THERAPEUTIC_AREA,
        PRODUCT_NAME,
        BASE_TACTIC,
        ACTUAL_TACTIC_CD,
        AGGREGATE_DATE,
        IDENTIFIED_FLAG,
        PARTY_CLASS,
        CUSTOMER_TYPE,
        PARTY_SUBTYPE,  
        TACTIC_CATEGORY,
        TACTIC_STREAM,
        TACTIC_SUB_STREAM,
        ACTIVITY_SOURCE,
        ACTIVITY_OFFER_DESCRIPTION,
        ACTIVITY_EM_NUMBER,
        ACTIVITY_EM_NUMBER_WITH_AB_SPLIT,
        LEAD_SOURCE,
        WEB_LEAD_SOURCE,
        IS_ACTIVE,
        GEO_REGION_CD,
        MS_DIGITAL_SEGMENT,
        SMA_DIGITAL_SEGMENT,
        ALZ_DIGITAL_SEGMENT,
        TOTAL_SENDS,
        TOTAL_OPENS,
        TOTAL_CLICKS,
        TOTAL_BOUNCES,
        CASE WHEN TOTAL_SENDS - TOTAL_BOUNCES < 0 THEN 0 ELSE TOTAL_SENDS - TOTAL_BOUNCES END AS TOTAL_DELIVERED,
        KPI_LEVEL
        FROM
(        
SELECT  THERAPEUTIC_AREA,
        PRODUCT_NAME,
        BASE_TACTIC,
        ACTUAL_TACTIC_CD,
        TIME_DT AS AGGREGATE_DATE,
        IDENTIFIED_FLAG,
        PARTY_CLASS,
        CUSTOMER_TYPE,
        PARTY_SUBTYPE,    
        TACTIC_CATEGORY,
        TACTIC_STREAM,
        TACTIC_SUB_STREAM,
        ACTIVITY_SOURCE,
        ACTIVITY_OFFER_DESCRIPTION,
        ACTIVITY_EM_NUMBER,
        ACTIVITY_EM_NUMBER_WITH_AB_SPLIT,
        LEAD_SOURCE,
        WEB_LEAD_SOURCE,
        IS_ACTIVE,
        GEO_REGION_CD,
        MS_DIGITAL_SEGMENT,
        SMA_DIGITAL_SEGMENT,
        ALZ_DIGITAL_SEGMENT,
        COUNT(CASE WHEN UPPER(ACTIVITY_TYPE) = 'EMAIL SENT' THEN MDM_ID END) AS TOTAL_SENDS,
        COUNT(CASE WHEN UPPER(ACTIVITY_TYPE) = 'EMAIL OPENED' THEN MDM_ID END) AS TOTAL_OPENS,
        COUNT(CASE WHEN UPPER(ACTIVITY_TYPE) = 'CLICKED LINK ON EMAIL' THEN MDM_ID END) AS TOTAL_CLICKS,
        COUNT(CASE WHEN UPPER(ACTIVITY_TYPE) = 'EMAIL BOUNCED' THEN MDM_ID END) AS TOTAL_BOUNCES,
        'Overall_Level' AS KPI_LEVEL
        FROM __SNOWFLAKE_NGCA_DB__.MCE.SFMC_EMAIL_ENG_BASE WHERE OVERALL_DUPLICATE_FLAG = 0 AND UPPER(UNSUBCRIBE_CLICKS_FLAG) = 'N' AND UPPER(FIREWALL_CLICK_FLAG) = 'N'
        GROUP BY (THERAPEUTIC_AREA,PRODUCT_NAME,BASE_TACTIC,ACTUAL_TACTIC_CD,TIME_DT,IDENTIFIED_FLAG,PARTY_CLASS,CUSTOMER_TYPE,PARTY_SUBTYPE,TACTIC_CATEGORY,TACTIC_STREAM,TACTIC_SUB_STREAM, ACTIVITY_SOURCE,
        ACTIVITY_OFFER_DESCRIPTION,
        ACTIVITY_EM_NUMBER,
        ACTIVITY_EM_NUMBER_WITH_AB_SPLIT,
        WEB_LEAD_SOURCE,IS_ACTIVE,
        GEO_REGION_CD,MS_DIGITAL_SEGMENT,SMA_DIGITAL_SEGMENT,ALZ_DIGITAL_SEGMENT)
        
        UNION ALL

SELECT  THERAPEUTIC_AREA,
        PRODUCT_NAME,
        BASE_TACTIC,
        ACTUAL_TACTIC_CD,
        MONTH_DT AS AGGREGATE_DATE,
        IDENTIFIED_FLAG,
        PARTY_CLASS,
        CUSTOMER_TYPE,
        PARTY_SUBTYPE,    
        TACTIC_CATEGORY,
        TACTIC_STREAM,
        TACTIC_SUB_STREAM,
        ACTIVITY_SOURCE,
        ACTIVITY_OFFER_DESCRIPTION,
        ACTIVITY_EM_NUMBER,
        ACTIVITY_EM_NUMBER_WITH_AB_SPLIT,
        LEAD_SOURCE,
        WEB_LEAD_SOURCE,
        IS_ACTIVE,
        GEO_REGION_CD,
        MS_DIGITAL_SEGMENT,
        SMA_DIGITAL_SEGMENT,
        ALZ_DIGITAL_SEGMENT,
        COUNT(CASE WHEN UPPER(ACTIVITY_TYPE) = 'EMAIL SENT' THEN MDM_ID END) AS TOTAL_SENDS,
        COUNT(CASE WHEN UPPER(ACTIVITY_TYPE) = 'EMAIL OPENED' THEN MDM_ID END) AS TOTAL_OPENS,
        COUNT(CASE WHEN UPPER(ACTIVITY_TYPE) = 'CLICKED LINK ON EMAIL' THEN MDM_ID END) AS TOTAL_CLICKS,
        COUNT(CASE WHEN UPPER(ACTIVITY_TYPE) = 'EMAIL BOUNCED' THEN MDM_ID END) AS TOTAL_BOUNCES,
        'Monthly_Level' AS KPI_LEVEL
        FROM __SNOWFLAKE_NGCA_DB__.MCE.SFMC_EMAIL_ENG_BASE WHERE MONTHLY_DUPLICATE_FLAG = 0 AND UPPER(UNSUBCRIBE_CLICKS_FLAG) = 'N' AND UPPER(FIREWALL_CLICK_FLAG) = 'N'
        GROUP BY (THERAPEUTIC_AREA,PRODUCT_NAME,BASE_TACTIC,ACTUAL_TACTIC_CD,MONTH_DT,IDENTIFIED_FLAG,PARTY_CLASS,CUSTOMER_TYPE,PARTY_SUBTYPE,TACTIC_CATEGORY,TACTIC_STREAM,TACTIC_SUB_STREAM, ACTIVITY_SOURCE,
        ACTIVITY_OFFER_DESCRIPTION,
        ACTIVITY_EM_NUMBER,
        ACTIVITY_EM_NUMBER_WITH_AB_SPLIT,
        WEB_LEAD_SOURCE,IS_ACTIVE,
        GEO_REGION_CD,MS_DIGITAL_SEGMENT,SMA_DIGITAL_SEGMENT,ALZ_DIGITAL_SEGMENT)
        
        UNION ALL
        
SELECT  THERAPEUTIC_AREA,
        PRODUCT_NAME,
        BASE_TACTIC,
        ACTUAL_TACTIC_CD,
        WEEK_BEGIN_DT AS AGGREGATE_DATE,
        IDENTIFIED_FLAG,
        PARTY_CLASS,
        CUSTOMER_TYPE,
        PARTY_SUBTYPE,   
        TACTIC_CATEGORY,
        TACTIC_STREAM,
        TACTIC_SUB_STREAM,
        ACTIVITY_SOURCE,
        ACTIVITY_OFFER_DESCRIPTION,
        ACTIVITY_EM_NUMBER,
        ACTIVITY_EM_NUMBER_WITH_AB_SPLIT,
        LEAD_SOURCE,
        WEB_LEAD_SOURCE,
        IS_ACTIVE,
        GEO_REGION_CD,
        MS_DIGITAL_SEGMENT,
        SMA_DIGITAL_SEGMENT,
        ALZ_DIGITAL_SEGMENT,
        COUNT(CASE WHEN UPPER(ACTIVITY_TYPE) = 'EMAIL SENT' THEN MDM_ID END) AS TOTAL_SENDS,
        COUNT(CASE WHEN UPPER(ACTIVITY_TYPE) = 'EMAIL OPENED' THEN MDM_ID END) AS TOTAL_OPENS,
        COUNT(CASE WHEN UPPER(ACTIVITY_TYPE) = 'CLICKED LINK ON EMAIL' THEN MDM_ID END) AS TOTAL_CLICKS,
        COUNT(CASE WHEN UPPER(ACTIVITY_TYPE) = 'EMAIL BOUNCED' THEN MDM_ID END) AS TOTAL_BOUNCES,
        'Weekly_Level' AS KPI_LEVEL
        FROM __SNOWFLAKE_NGCA_DB__.MCE.SFMC_EMAIL_ENG_BASE WHERE WEEKLY_DUPLICATE_FLAG = 0 AND UPPER(UNSUBCRIBE_CLICKS_FLAG) = 'N' AND UPPER(FIREWALL_CLICK_FLAG) = 'N'
        GROUP BY (THERAPEUTIC_AREA,PRODUCT_NAME,BASE_TACTIC,ACTUAL_TACTIC_CD,WEEK_BEGIN_DT,IDENTIFIED_FLAG,PARTY_CLASS,CUSTOMER_TYPE,PARTY_SUBTYPE,TACTIC_CATEGORY,TACTIC_STREAM,TACTIC_SUB_STREAM, ACTIVITY_SOURCE,
        ACTIVITY_OFFER_DESCRIPTION,
        ACTIVITY_EM_NUMBER,
        ACTIVITY_EM_NUMBER_WITH_AB_SPLIT,
        WEB_LEAD_SOURCE,IS_ACTIVE,
        GEO_REGION_CD,MS_DIGITAL_SEGMENT,SMA_DIGITAL_SEGMENT,ALZ_DIGITAL_SEGMENT)
)                
);
