
/*
ADU_MT_NON_PROMOTIONAL_METRICS
Purpose
    - Non-Promotional metrics on customer id-time bucket level for field suggestions.
Change Log
    - 2021-07-26 - vshetiya - Created

*/

USE ROLE __SNOWFLAKE_NGCA_CIM_DEPLOY_RL__; 

CREATE OR REPLACE VIEW __SNOWFLAKE_NGCA_DB__.MCE.ADU_MT_NON_PROMOTIONAL_METRICS
COMMENT = 'VIEW CONTAINING THE NON-PROMOTIONAL METRICS DATA FOR HCPs'
AS 
(
 WITH 
 ab_test AS
 (
    SELECT MK_ACCOUNT_VNT_ID,
           TO_DATE(DATEADD(DAY,-2,LAST_DAY(RESULT_DATE,'week'))) AS TIME_BUCKET_DATE,
           'ADUHELM' AS PRODUCT_NAME,
           PATIENT_ID,
           TEST_RESULT
    FROM __SNOWFLAKE_NGCA_DB__.CIM.AD_MAYO_LABCORP_FACT
    WHERE MK_ACCOUNT_VNT_ID <> '-1'
    AND UPPER(DATA_SOURCE) = 'MAYO'	
 )

SELECT
    MK_ACCOUNT_VNT_ID AS CUSTOMER_ID,
    PRODUCT_NAME,
    TIME_BUCKET_DATE,
    'M101' AS METRIC_ID,
    'HCP_Number_of_AB_Positive_Test_Result_Sponsored_Testing' AS METRIC_NAME,
     COUNT(DISTINCT(PATIENT_ID)) AS METRIC_VALUE
FROM ab_test
WHERE UPPER(TEST_RESULT) = 'POSITIVE'
GROUP BY MK_ACCOUNT_VNT_ID,PRODUCT_NAME,TIME_BUCKET_DATE
  
UNION ALL
 
SELECT
    MK_ACCOUNT_VNT_ID AS CUSTOMER_ID,
    PRODUCT_NAME,
    TIME_BUCKET_DATE,
    'M102' AS METRIC_ID,
    'HCP_Number_of_AB_Negative_Test_Result_Sponsored_Testing' AS METRIC_NAME,
    COUNT(DISTINCT(PATIENT_ID)) AS METRIC_VALUE
FROM ab_test
WHERE UPPER(TEST_RESULT) = 'NEGATIVE'
GROUP BY MK_ACCOUNT_VNT_ID,PRODUCT_NAME,TIME_BUCKET_DATE
 
UNION ALL
   
SELECT 
    CUSTOMER_ID,
    PRODUCT_NAME,
    MAX(TO_DATE(DATE_OF_ACTIVITY)) AS TIME_BUCKET_DATE,
    'M103' AS METRIC_ID,
    'HCP_Last_Call_Activity_Date' AS METRIC_NAME,
    1 AS METRIC_VALUE
FROM (
                
    SELECT MK_ACCOUNT_VNT_ID AS CUSTOMER_ID,            
           CALL_START_DATE AS DATE_OF_ACTIVITY,
           ACCOUNT_TYPE,                      
           'ADUHELM' AS PRODUCT_NAME
    FROM __SNOWFLAKE_NGCA_DB__.CIM.FIELD_CALL_ACTIVITY_FACT  
    WHERE 
	    (CALL_START_DATE) <= (SYSDATE()) 
        AND (UPPER(FIRST_PRODUCT) = 'ADUHELM' OR UPPER(SECOND_PRODUCT) = 'ADUHELM' OR UPPER(THIRD_PRODUCT) = 'ADUHELM' 
	                                          OR UPPER(FOURTH_PRODUCT) = 'ADUHELM' OR UPPER(FIFTH_PRODUCT) = 'ADUHELM')
        AND UPPER(FIELD_FORCE_NAME) IN ('AD','AD-AAL','AD-ADRM','AD-MSL','AD-TBM','AD MSL')
        
     ) call_activity_fact
WHERE  UPPER(ACCOUNT_TYPE) = 'HCP'
GROUP BY CUSTOMER_ID,PRODUCT_NAME

UNION ALL

SELECT 
    CUSTOMER_ID,
    PRODUCT_NAME,
    TIME_BUCKET_DATE,
    'M104' AS METRIC_ID,
    'HCO_Number_Of_Aduhelm_Shipment' AS METRIC_NAME,
    SUM(KPI_NUMERATOR) AS METRIC_VALUE
FROM (
    SELECT RIGHT(ACCOUNT_1,18) AS CUSTOMER_ID,
           TO_DATE(DATEADD(DAY,-2,LAST_DAY(KPI_DATE,'week'))) AS TIME_BUCKET_DATE,
           KPI_PRODUCT AS PRODUCT_NAME,
           ROUND(KPI_NUMERATOR) AS KPI_NUMERATOR
    FROM __SNOWFLAKE_NGCA_DB__.CIM.AD_KPI_SHIPMENT
    WHERE
        UPPER(REFERRAL_TYPE) = 'COMMERCIAL'
        AND UPPER(DATA_SOURCE) = 'VALUETRAK'
        AND KPI_PRODUCT = 'ADUHELM'
        AND ACCOUNT_1 IS NOT NULL
        AND ACCOUNT_1 <> 'VNID-1'
        AND UPPER(TIME_TYPE) = 'DAY'
        AND ACCOUNT_1 NOT LIKE '%ZIP%'
 ) shipment
GROUP BY CUSTOMER_ID,PRODUCT_NAME,TIME_BUCKET_DATE
   
);

GRANT SELECT ON __SNOWFLAKE_NGCA_DB__.MCE.ADU_MT_NON_PROMOTIONAL_METRICS TO ROLE IHUB_QRY_RL; 
